# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\enroll.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(933, 609)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet(".QFrame#frame{border-image: url(:/img/img/Desktop_-_7.png)}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.enrollBtn = QtWidgets.QPushButton(self.frame)
        self.enrollBtn.setGeometry(QtCore.QRect(640, 440, 93, 28))
        self.enrollBtn.setStyleSheet("  background-color: transparent;\n"
"  border: none;")
        self.enrollBtn.setText("")
        self.enrollBtn.setObjectName("enrollBtn")
        self.loginBtn = QtWidgets.QPushButton(self.frame)
        self.loginBtn.setGeometry(QtCore.QRect(750, 440, 121, 31))
        self.loginBtn.setStyleSheet("  background-color: transparent;\n"
"  border: none;")
        self.loginBtn.setText("")
        self.loginBtn.setObjectName("loginBtn")
        self.idlineEdit = QtWidgets.QLineEdit(self.frame)
        self.idlineEdit.setGeometry(QtCore.QRect(570, 260, 231, 31))
        self.idlineEdit.setStyleSheet("  background-color: transparent;\n"
"  border: none;")
        self.idlineEdit.setObjectName("idlineEdit")
        self.pwdlineEdit = QtWidgets.QLineEdit(self.frame)
        self.pwdlineEdit.setGeometry(QtCore.QRect(580, 310, 231, 31))
        self.pwdlineEdit.setStyleSheet("  background-color: transparent;\n"
"  border: none;")
        self.pwdlineEdit.setObjectName("pwdlineEdit")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(560, 360, 241, 81))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import ui.imgenroll
