# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(959, 559)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet(".QFrame#frame{\n"
" background-color: transparent;\n"
"border-image: url(:/img/img/Desktop_-_1.png);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.enrollBtn = QtWidgets.QPushButton(self.frame)
        self.enrollBtn.setGeometry(QtCore.QRect(430, 500, 51, 21))
        self.enrollBtn.setStyleSheet("  background-color: transparent;\n"
"  border: none;")
        self.enrollBtn.setText("")
        self.enrollBtn.setObjectName("enrollBtn")
        self.loginBtn = QtWidgets.QPushButton(self.frame)
        self.loginBtn.setGeometry(QtCore.QRect(240, 480, 181, 31))
        self.loginBtn.setStyleSheet("  background-color: transparent;\n"
"  border: none;")
        self.loginBtn.setText("")
        self.loginBtn.setObjectName("loginBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(210, 320, 251, 41))
        self.lineEdit.setStyleSheet("  background-color: transparent;\n"
"  border: none;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 390, 251, 41))
        self.lineEdit_2.setStyleSheet("  background-color: transparent;\n"
"  border: none;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import ui.imghome
